### ISSUE TITLE
请问一下这个对flash制作的要求

### ISSUE THREAD

**Issue by StaticCoder** [yyued/SVGA-FLConverter#2]
我们现在使用svgaplayer在移动端进行动画展示，动画制作使用flash。
使用插件转换后放在移动端播放（或者在svga预览器中播放）出现一些问题：有时候动画错位，有时候只播放动画的前面一部分，不过也有时候是完美运行的。请问这种问题怎么解决呢？这个在flash制作时与常规flash制作有什么区别，有什么需要注意的地方？

**Comment by PonyCui** [comment]
请把源文件发送至 help@svga.io

**Comment by PonyCui** [comment]
有部分属性是不支持的

**Comment by StaticCoder** [comment]
我们本来拟用flajson+图片的方案，UI哥们做的动画一直用的是影片剪辑格式，现在用SVGA，还是用的影片剪辑格式，所以出现转换不完整的问题，把动画改成元件格式就好了，我也不知道其中原因。
ps:很感谢，很优秀的一套动画方案，期待后期支持更多的特效。

**Comment by PonyCui** [comment]
好的
